"""
Walking Directions Service - Uses Google Gemini to generate walking directions.
"""

import os
import json
import asyncio
import logging
from typing import Optional, List
from pydantic import BaseModel, Field
from google import genai

logger = logging.getLogger(__name__)


# ============================================================================
# Response Models
# ============================================================================

class Checkpoint(BaseModel):
    """Checkpoint at the end of a direction segment"""
    name: str
    lat: Optional[float] = None
    lng: Optional[float] = None
    landmark_hint: Optional[str] = None  # Visual cue to identify this location


class DirectionSegment(BaseModel):
    """A segment of walking directions between two waypoints"""
    segment_index: int
    from_id: str
    to_id: str
    summary: str
    distance_estimate_mi: Optional[float] = None
    estimated_duration_min: Optional[float] = None
    steps: List[str]
    checkpoint: Checkpoint


class Waypoint(BaseModel):
    """A waypoint along the walking route"""
    id: str
    name: str
    lat: Optional[float] = None
    lng: Optional[float] = None
    description: str
    type: str  # "start", "intermediate", or "end"


class WalkingRoute(BaseModel):
    """Walking route generated by Gemini"""
    route_name: str
    start_location_query: str
    end_location_query: str
    notes: str
    total_distance_mi: Optional[float] = None
    estimated_duration_min: Optional[float] = None
    safety_note: str
    waypoints: List[Waypoint]
    directions: List[DirectionSegment]


# ============================================================================
# Walking Directions Service
# ============================================================================

class WalkingDirectionsService:
    """Service for generating walking directions using Gemini."""
    
    SYSTEM_PROMPT = """You are a helpful local walking guide. Output ONLY valid JSON.

Your job is to create DETAILED, tourist-friendly walking directions with visual landmarks and helpful hints so someone unfamiliar with the area can navigate confidently.

====================================
JSON OUTPUT SCHEMA
====================================

{
  "route_name": string,
  "start_location_query": string,
  "end_location_query": string,
  "notes": string,
  "total_distance_mi": number | null,
  "estimated_duration_min": number | null,
  "safety_note": string,
  "waypoints": [
    {
      "id": string,
      "name": string,
      "lat": number | null,
      "lng": number | null,
      "description": string,
      "type": "start" | "intermediate" | "end"
    }
  ],
  "directions": [
    {
      "segment_index": integer,
      "from_id": string,
      "to_id": string,
      "summary": string,
      "distance_estimate_mi": number | null,
      "estimated_duration_min": number | null,
      "steps": [string],
      "checkpoint": {
        "name": string,
        "lat": number | null,
        "lng": number | null,
        "landmark_hint": string
      }
    }
  ]
}

====================================
CRITICAL: DETAILED DIRECTIONS STYLE
====================================

Make directions HELPFUL and SPECIFIC for tourists:

1. SUMMARY: Write a clear, action-oriented summary like:
   - "Walk along the scenic Embarcadero waterfront to Pier 39"
   - "Head uphill through Chinatown to the Dragon Gate"
   
2. STEPS: Each step should include WHAT TO LOOK FOR:
   BAD: "Turn left on Market Street"
   GOOD: "Turn left onto Market Street - look for the historic F-line streetcars running down the center"
   
   BAD: "Continue to Fisherman's Wharf"  
   GOOD: "Continue toward Fisherman's Wharf - you'll smell fresh seafood and see the famous crab stands ahead"

3. CHECKPOINT landmark_hint: Describe HOW TO RECOGNIZE you've arrived:
   - "Look for the large red pagoda-style gate with green roof tiles"
   - "You'll see sea lions lounging on wooden docks - you can hear them barking!"
   - "The bridge's iconic orange towers will be directly ahead of you"
   - "Look for the vintage cable car turnaround with the circular platform"

4. Include sensory details when relevant:
   - Sounds: "You'll hear street musicians", "Listen for the cable car bells"
   - Sights: "Look for the red brick building", "The blue bay will be on your right"
   - Smells: "The aroma of sourdough bread from Boudin Bakery"

5. Mention helpful landmarks along the way:
   - Notable buildings, statues, or art installations
   - Parks, plazas, or open spaces
   - Popular restaurants or shops as reference points

====================================
RULES
====================================

- Use MILES for distances
- Create 3-8 waypoints depending on route length
- Each segment should have 3-6 detailed steps
- Write for someone who has NEVER been to this area
- Be warm and encouraging in tone
- Include safety tips if relevant (crosswalks, busy intersections)

====================================
OUTPUT FORMAT
====================================

- Output ONLY a JSON object, no markdown or explanation
- JSON must be syntactically valid"""

    def __init__(self):
        self.api_key = os.getenv("GOOGLE_API_KEY")
        if not self.api_key:
            logger.warning("GOOGLE_API_KEY not found in environment variables")
        self.client: Optional[genai.Client] = None
    
    def _get_client(self) -> genai.Client:
        """Get or create the Gemini client."""
        if self.client is None:
            if not self.api_key:
                raise ValueError("GOOGLE_API_KEY is not configured")
            self.client = genai.Client(api_key=self.api_key)
        return self.client
    
    async def get_walking_directions(
        self,
        start_location: str,
        end_location: str
    ) -> WalkingRoute:
        """
        Get walking directions from start to end location using Gemini.
        
        Args:
            start_location: The starting point (e.g., "Tokyo Skytree")
            end_location: The destination (e.g., "Tokyo Tower")
            
        Returns:
            WalkingRoute object with waypoints and directions
            
        Raises:
            ValueError: If API key is not configured
            Exception: If Gemini API call fails or response parsing fails
        """
        client = self._get_client()
        
        user_prompt = f"Walk from {start_location} to {end_location}"
        
        logger.info(f"Requesting walking directions: {user_prompt}")
        
        try:
            # Run synchronous API in thread pool to avoid SSL issues
            response = await asyncio.to_thread(
                client.models.generate_content,
                model="gemini-2.0-flash",
                contents=self.SYSTEM_PROMPT + "\n\n" + user_prompt,
                config={
                    "response_mime_type": "application/json",
                    "temperature": 0.7,
                }
            )
            
            content = response.text
            if not content:
                raise ValueError("Empty response from Gemini")
            
            logger.debug(f"Gemini response: {content[:500]}...")
            
            # Parse the JSON response
            route_data = json.loads(content)
            
            # Validate and convert to WalkingRoute model
            walking_route = WalkingRoute(**route_data)
            
            logger.info(
                f"Successfully generated route: {walking_route.route_name} "
                f"({walking_route.total_distance_mi or 'unknown'} mi, "
                f"{walking_route.estimated_duration_min or 'unknown'} min)"
            )
            
            return walking_route
            
        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse Gemini response as JSON: {e}")
            raise ValueError(f"Invalid JSON response from Gemini: {e}")
        except Exception as e:
            logger.error(f"Gemini API call failed: {e}")
            raise


# Singleton instance
walking_directions_service = WalkingDirectionsService()


def get_walking_directions_service() -> WalkingDirectionsService:
    """Get the walking directions service instance."""
    return walking_directions_service
